// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD665Q0nISVXaAWlo97pgzVZ3zadKHZy2c',
    appId: '1:607630878747:web:c532e4cf2ba73dda90f0be',
    messagingSenderId: '607630878747',
    projectId: 'turnikesistem-82480',
    authDomain: 'turnikesistem-82480.firebaseapp.com',
    databaseURL: 'https://turnikesistem-82480-default-rtdb.firebaseio.com',
    storageBucket: 'turnikesistem-82480.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ycAwu5UpN0vOmRum0mpWbn-8QcgmjLQ',
    appId: '1:607630878747:android:234d434357f2dae490f0be',
    messagingSenderId: '607630878747',
    projectId: 'turnikesistem-82480',
    databaseURL: 'https://turnikesistem-82480-default-rtdb.firebaseio.com',
    storageBucket: 'turnikesistem-82480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_q6mwIqmg0n1_4sILlbrT9RThIWSqOM',
    appId: '1:607630878747:ios:9907347f0273789690f0be',
    messagingSenderId: '607630878747',
    projectId: 'turnikesistem-82480',
    databaseURL: 'https://turnikesistem-82480-default-rtdb.firebaseio.com',
    storageBucket: 'turnikesistem-82480.firebasestorage.app',
    iosBundleId: 'com.example.turnike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_q6mwIqmg0n1_4sILlbrT9RThIWSqOM',
    appId: '1:607630878747:ios:9907347f0273789690f0be',
    messagingSenderId: '607630878747',
    projectId: 'turnikesistem-82480',
    databaseURL: 'https://turnikesistem-82480-default-rtdb.firebaseio.com',
    storageBucket: 'turnikesistem-82480.firebasestorage.app',
    iosBundleId: 'com.example.turnike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD665Q0nISVXaAWlo97pgzVZ3zadKHZy2c',
    appId: '1:607630878747:web:38c807ec9711491e90f0be',
    messagingSenderId: '607630878747',
    projectId: 'turnikesistem-82480',
    authDomain: 'turnikesistem-82480.firebaseapp.com',
    databaseURL: 'https://turnikesistem-82480-default-rtdb.firebaseio.com',
    storageBucket: 'turnikesistem-82480.firebasestorage.app',
  );
}
